version: '3.5'

services:
  bot:
    build: .
    image: labbsr0x/big-brother-bot:latest
    environment:
      - ETCD_URLS=http://etcd:2379
      - TELEGRAM_TOKEN=<your telegram token>
      - DEBUG=*
    ports:
      - 3001:3000

  etcd:
    image: quay.io/coreos/etcd:v3.2.25
    ports:
      - 2379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
